# this tool is designed to save the aniamtion plan(.md) generated by animation agent

import os
from datetime import datetime
import re

def sanitize_filename(text: str) -> str:
    """
    Sanitize input to create a safe filename.
    Removes unsafe characters and replaces spaces with underscores.
    """
    # Remove all forbidden characters
    forbidden = r'[<>:"/\\|?*=]'
    text = re.sub(forbidden, '', text)

    # Replace spaces and other safe formatting
    text = text.lower()
    text = re.sub(r"\s+", "_", text.strip())
    return text


def save_animation_plan(markdown: str, user_input: str, folder: str = "animation_plan") -> str:
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    full_folder = os.path.join(base_dir, folder)
    os.makedirs(full_folder, exist_ok=True)

    base_name = sanitize_filename(user_input[:80])
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{base_name}__{timestamp}.md"
    filepath = os.path.join(full_folder, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(markdown)

    return filepath
